# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Update version in all needed files"
inputs:
  version:
    description: "Version to be set"
    required: true
  gha_token:
    description: "GHA bot token"
    required: true

runs:
  using: composite
  steps:
    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Install git-conventional-commits
      shell: bash
      run: |
        npm i git-conventional-commits

    - name: Update version in files
      shell: bash
      run: |
        python $GITHUB_WORKSPACE/.github/actions/update-version/update_version.py "$VERSION"
      env:
        VERSION: ${{ inputs.version }}

    - name: Generate changelog
      shell: bash
      run: |
        npx git-conventional-commits changelog --file CHANGELOG.md --release "$VERSION"
      env:
        VERSION: ${{ inputs.version }}

    - name: Setup git config
      shell: bash
      run: |
        git config user.name  "${{ steps.app-token.outputs.app-slug }}[bot]"
        git config user.email "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"

    - name: Commit
      shell: bash
      run: |
        git add galaxy.yml roles/oneagent/vars/version.yml CHANGELOG.md
        git commit -m "chore: Update the collection version to $VERSION"
        git push origin HEAD:"$VERSION"
      env:
        VERSION: ${{ inputs.version }}

    - name: Create Pull Request
      shell: bash
      run: |
        gh pr create --title "Version update: $VERSION" --body "" --head "$VERSION" --base "master"
        PR_URL=""
        for i in {1..60}; do
          PR_JSON=$(gh pr list --head "$VERSION" --state open --json number,url --jq '.[0]')
          PR_URL=$(echo "$PR_JSON" | jq -r '.[0].url')
          if [[ -n "$PR_URL" && "$PR_URL" != "null" ]]; then
            echo "Pull request created: $PR_URL"
            echo "PR_NUMBER=$(echo "$PR_JSON" | jq -r .number)" >> "$GITHUB_ENV"
            echo "PR_URL=$(echo "$PR_JSON" | jq -r .url)" >> "$GITHUB_ENV"
            break
          fi
          echo "Waiting for pull request to be created..."
          sleep 10
        done

        echo "Pull request was not created within timeout."
        exit 1
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        VERSION: ${{ inputs.version }}

    - name: Wait for checks
      shell: bash
      run: |
        echo "Waiting for all checks to pass on PR #${PR_NUMBER}..."
        for i in {1..60}; do
          STATUS=$(gh pr checks $PR_NUMBER --json status -q '.status')
          echo "Current status: $STATUS"
          if [ "$STATUS" = "completed" ]; then
            echo "All checks completed!"
            break
          fi
          sleep 10
        done
        
        echo "Pull request status checks did not pass within timeout."
        exit 1
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Merge pull request
      shell: bash
      run: |
        gh pr merge "$PR_URL" --merge --delete-branch
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

